function EEG_Step2_SourceReconstruction()
% Source reconstruction and extraction of source values inside an ROI.
% In this case, the visual primary and secondary cortical areas (V1V2) is  
% defined as default.
%
%   INPUTS: 
%       none
%
%   OUPUTS:
%       none
%
%   SCRIPTS USED: 
%       Source_Brainstorm_Trials_kernel.m, ReorganizeSourceMatrices.m
%
%   FILES USED: 
%       paths.study/Subjects/SubName/EEG/Preprocessed/dataTrials_for_BST_SubName_CondName.mat (Data all processed, with the trial structure kept, in a format that can be uploaded to Brainstorm software: Fieldtrip structure with only one time vector instead of one time cell for each trial)
%		paths.study/Subjects/SubName/EEG/Originals/SubName.elec (3D positions of each electrode as measured with digitization) 
% 		paths.study/Subjects/SubName/MRI/Freesurfer (it has to include the files: mri/T1.mgz, surf/rh.pial, 
% 		surf/lh.pial, label/lh.BA_exvivo.annot, label/rh.BA_exvivo.annot, label/BA_exvivo.ctab)
%       paths.m, params.m
%
%   FILES GENERATED BY MANUAL MANIPULATION:
%		paths.study/Subjects/SubName/EEG/V1V2_vertices.mat (Vertices numbers associated with the ROIs V1V2: structure with V1V2(1).Vertices-->numbers of left V1V2 vertices; V1V2(2).Vertices-->numbers of right V1V2 vertices)
%       paths.study/Subjects/SubName/EEG/cortex.mat (Vertices associated with the all cortex: structure with cortex.Vertices---> [# vertices x 3 positions in 3D])
% 
%   FILES GENERATED: 
%       paths.brainstorm_func/SubName/CondName/data_dataTrials_for_BST_SubName_CondName_TrialNum_matlab.mat (Trials with units recognized by Brainstorm: Brainstorm file)
%       paths.brainstorm_func/SubName/CondName/results_MN_EEG_KERNEL_*.mat (Kernel for the source reconstruction: Brainstorm file)
%       paths.brainstorm_func/SubName/CondName/matrix_scout_*.mat (x3) (Source values inside the ROIs of interest: 1) V1&V2 Left; 2) V1&V2 Right; 3)V1&V2 Left & V1&V2 Right: Brainstorm file)
%       paths.brainstorm_func/SubName/CondName/data_dataTrials_for_BST_SubName_CondName_TrialNum_average_*.mat (Trial average: Brainstorm file)
%	    paths.study/Subjects/SubName/EEG/Delays/CD_CondNameVisualField_LeftBrainV1V2.mat (Current source densities (pA.m) of each brain vertice, trial and time point for the left brain visual cortex: [#trials x #vertices x #timepoints])
%       paths.study/Subjects/SubName/EEG/Delays/CD_CondNameVisualField_RightBrainV1V2.mat (Current source densities (pA.m) of each brain vertice, trial and time point for the right brain visual cortex: [#trials x #vertices x #timepoints])
%       paths.study/Study_Group_Results/time_vec.mat (Vector of the time sample of the EEG epochs [1 x #time points])
%       (CondName = condition, SubName = subject's name, TrialNum = trial number)
%
%   EXTERNAL PACKAGES USED:
%       Brainstorm
%    
%   SYNTAX:
%       EEG_Step2_SourceReconstruction()
%
%   NOTE I: 
%       To run this part, some manual work has to be done BEFORE in Brainstorm:
%               1. Create a study
%               2. Import Freesurfer folder of each subject, with 15000 vertices on the cortex
%               3. Edit fiducials points (LPA,RPA,nasion, AC, PC, IH)
%               4. Generete BEM surfaces on the MRI using Brainstorm algorithm
%               5. Import files: dataTrials_for_BST_SubName_CondName.mat (MEG/EEG Fieldtrip data format) and rename the folder to CondName.
%               6. Add EEG position and head points file SubName.elec (add EEG positions and not electrode file). 
%               7. Register with MRI and adjust when necessary 
%               8. Compute head model (OpenMEEG on cortex)
%               9. On the anatomy of each subject, create 2 atlas with the following names and structures inside by copying it from the Brodmann atlas:
%                   1) V1V2_separate (V1&V2 Left; V1&V2 Right)
%                   2) V1V2_together (V1&V2 Left&V1&V2 Right) 
%               10. On the subject EEG folder (../Subjects/SubName/EEG) save the vertices and cortex structure:
%                   1) V1V2_vertices.mat 
%                   2) cortex.mat 
%
%   NOTE II: 
%       Save and close Brainstorm before starting this script.
%       Here a new Brainstorm window will be opened (because Brainstorm has to 
%       be open for their scripts to run, although no image/display of the subjects 
%       can't be open)
%
%   NOTE II: 
%       I commented bst_scout_value script from brainstorm at line 56: 
%          > From: if isSignFlip && (nComponents == 1) && ~isempty(Orient) 
%       && ~strcmpi(ScoutFunction,'all') && (size(F,1) > 1) && ~all(F(:) > 0) 
%          > To:   if isSignFlip && (nComponents == 1) && ~isempty(Orient) 
%       && (size(F,1) > 1) && ~all(F(:) > 0) 
%
% -------------------------------------------------------------------------
% Author: Rita Oliveira
% Email: rita.oliveira.uni@gmail.com
% Laboratory for Research in Neuroimaging (LREN)
% Department of Clinical Neuroscience, Lausanne  University Hospital and University of Lausanne
% Mont-Paisible 16, CH-1011 Lausanne, Switzerland
%
% Last updated: 10/01/2022
% -------------------------------------------------------------------------

clc
clear all
close all

% Load paths and params
load('paths.mat')
load('params.mat')

sub_list    = params.sub_list;
cond_list   = params.cond_list;

addpath(genpath((paths.scripts)))
cd(paths.brainstorm)
brainstorm

% Transform data so that Fieldtrip units are well recognized
Source_Brainstorm_Trials_kernel(sub_list,cond_list,'matlab',paths.brainstorm_func)

% Estimate source kernel
Source_Brainstorm_Trials_kernel(sub_list,cond_list,'source',paths.brainstorm_func)

% Extract the source time course inside regions of interest
Source_Brainstorm_Trials_kernel(sub_list,cond_list,'scout all V1V2',paths.brainstorm_func)

% Create average of the trials (easier to visualize)
Source_Brainstorm_Trials_kernel(sub_list,cond_list,'average',paths.brainstorm_func)

brainstorm stop

% Reorganize data from the source reconstruction using brainstorm into more intituitive data matrices
ReorganizeSourceMatrices(sub_list,cond_list,{'V1V2'},paths.brainstorm_func,paths.data,paths.group)

cd(fullfile(paths.scripts,'main'))


end
